### PR TITLE
Optimize img folder

### PR DESCRIPTION
**Pull request by DirtyF**
Saved 600ko over 2.7Mo, 22% overall with [ImageOptim](https://imageoptim.com/mac). No quality loss.

imageoptim-jamstack

### CODE REVIEW

**Comment by jhabdas** [comment]
You could eke out more performance on the SVGs using [`svgo`](https://github.com/svg/svgo), but the gains will be negligible either way as the bottleneck without inlining svg images ([example](https://github.com/comfusion/after-dark/blob/v1.7.2/layouts/partials/favicon.html)) is almost always the network.

**Comment by DirtyF** [comment]
@jhabdas ImageOptim includes SVGO, all SVG were optimized

**Comment by eliwilliamson** [comment]
@DirtyF this is awesome! thank you, my only bit of feedback would be to include something that compressed images at build time for a more automated workflow - perhaps as a gulp task. Additionally, it would be nice to have something that not only compresses the existing images but also creates smaller scale images for smaller viewports - imagemagick comes to mind but i haven't touched that in a while. i'm sure there is something newer out to accomplish a similar effect. I've been meaning to do this myself but you beat me to the punch 🥇

**Comment by jhabdas** [comment]
I'd opened #48 for the suggestion made by @eliwilliamson. Feel free to reopen or use as reference.

**Comment by DirtyF** [comment]
@eliwilliamson I completely agree, but I though : small effort, big impact. Let's do a tiny step in the right direction :)

**Comment by DirtyF** [comment]
@eliwilliamson FYI you could also rely on a service like [Cloudinary](http://cloudinary.com/)

**Comment by jhabdas** [comment]
> @eliwilliamson FYI you could also rely on a service like Cloudinary

Based on personal experiences reliance on 3rd parties creates SPOF. Something to be aware of. If you did want a simple API to tap into for screenshots a little, and quick one has been proposed in #68. I tried it out and it's pretty neat.

**Comment by biilmann** [comment]
It seems regardless of what else we might want to do to improve image sizes and load times, this is obviously an improvement, so I'll go ahead and merge it in. Thanks @DirtyF !

**Pull request merged**
