### PR TITLE
feat(resources/articles): add article descriptions

### PR DESCRIPTION
**Pull request by jhabdas**
adds article descriptions using description meta, <del>truncated at 160 characters,</del> and improves the
treatment of article ux, helping them stand out more

articles-update

### CODE REVIEW

**Comment by jhabdas** [comment]
@calavera since you're working pulls, any idea why the build is failing? I tried to access the logs but got a 404 page. tried bumping the environment to a later version of Hugo but that didn't fix the problem.

**Comment by jhabdas** [comment]
I'll assume that's a big nope.

**Comment by erquhart** [comment]
I'm with the spirit of this, just needs a design review.

cc/ @eliwilliamson

**Comment by jhabdas** [comment]
I took care to ensure everything looked good on the responsive breakpoints. @eliwilliamson hope you like it.

**Comment by verythorough** [comment]
@jhabdas, it looks like the `truncate` function is what's breaking the build:
screen shot 2017-04-07 at 9 25 53 am
I'm guessing this is a Hugo version issue.

Since the descriptions are hard-coded into the data file (as opposed to pulled from a feed, for example), I think it's fair to ask humans to do the truncating by giving a length limit for descriptions given with article contributions.

For the design, I think @eliwilliamson will have comments, but he's very busy this week. From the screenshot, the design feels a bit overly bolded to me, but we'll see how it looks in the context on the page when the preview gets working.

I do like the idea of having descriptions and think it might also be worth including the title of the article website (like "Contentful" or "Habd.as").

**Comment by jhabdas** [comment]
@verythorough I like the idea of having the resources match both in title and description. As a first pass I wanted to pull full descriptions for preservation and to help illustrate [what will appear on SERPs](https://moz.com/pages/search_results) WRT description content provided.

Regarding the Hugo version, I already bumped to `0.19` [using these instructions](https://www.adamwills.io/blog/hugo-version-issues-netlify/) and watched the build fail. So my assumption is there's some kind of environment incompatibility which should probably get looked as the scope of the impact is broader than this particular pull.

Let's wait for feedback on the design. I have no qualms toning down the titles a bit, but it's helpful to look at things in context and the articles are currently dwarfed within the page due to other prominent elements of the design.

**Comment by verythorough** [comment]
The instructions you linked for bumping the version require setting an environment variable in the Netlify app. (That's the screenshot in Step 1.) Without that variable to refer to, the ternary in the last code snippet will return false and run the default `hugo` build command again.

I can see the argument for dynamically pulling article data (which would probably make sense to be applied to videos/thumbnails, and possibly even example screenshots, as well.) We'd have to account for what happens (mostly design-wise) when the data isn't available. Until we *are* dynamically pulling data, though, I don't see the need for `truncate`. Could you try without and see if the build succeeds? If there are other reasons for bumping the Hugo version, we can discuss those in a separate issue/PR.

**Comment by jhabdas** [comment]
Truncation removed. You didn't have to ask twice, I wasn't fighting it. 😉

**Comment by verythorough** [comment]
Yeah, you have to be a collaborator on the site to see site info, including the build log. Having publicly viewable build logs for use cases such as this is something worth considering. It's possible to mimic the Netlify build process for testing ([instructions here](https://www.netlify.com/blog/2016/10/18/how-our-build-bots-build-sites/)), but that seems like a lot to ask just to see a build log.

**Comment by verythorough** [comment]
As it turns out, I went to file an issue for the Netlify UI, and found it's already there, so we'll likely see  public build logs before too long.

In the meantime, I'm glad we've got your deploy preview working now. We probably won't have a chance to talk design with @eliwilliamson until next week.

**Comment by rafaelconde** [comment]
I would at least tone it down a bit, visually:
screenshot 2017-04-28 15 40 45

`
opacity: .7;
font-weight: 400;
margin-top: 16px;
font-size: 14px;
`

**Comment by calavera** [comment]
I agree with @rafaelconde. The current teal text is very hard to read.

**Comment by eliwilliamson** [comment]
i agree with @rafaelconde the monotone version looks cleaner however instead of using `opacity` to achieve this, let's use the greyscale variables defined in the config if possible.

**Comment by jhabdas** [comment]
Thanks for the feedback all. It sounds like we should slightly reduce the amount of pop given to the WIP treatment of titles, possibly increase contrast of the muted text and look to normalize style changes made, folding it back into the base style variables config. Did I capture that correctly? @calavera would you advise going with WCAG AA [conformance WRT contrast](https://www.w3.org/WAI/WCAG20/quickref/#qr-visual-audio-contrast-contrast) of the muted text?

@verythorough anything to add?

**Comment by jhabdas** [comment]
Closing as I have lost interest in improving this website. I will leave the branch until I decide to delete my fork.

**Pull request closed without merging**
