### PR TITLE
Adding Foundation to examples

### PR DESCRIPTION
**Pull request by stackrole-dev**
Adding https://foundation.stackrole.com/ to examples

### CODE REVIEW

**Comment by stackrole-dev** [comment]
Hi Netlify,

When i can expect this to be merged.

Thank you

**Comment by stackrole-dev** [comment]
Hi @philhawksworth,

Did not new who to tag, so tagging you here. When can i expect my starter be added to Jamstack.org

**Comment by munwr** [comment]
Hi @zachleat,

Thank you for adding this, it means a lot :)

**Comment by zachleat** [comment]
Really sorry about this, GitHub autoclosed a bunch of PRs when we released a new site design this morning and switched the default branch to `main`. Can you change the target to `main` and then I can reopen?

**Pull request closed without merging**
