### PR TITLE
docs(resources/articles): add JAMstack tutorial

### PR DESCRIPTION
**Pull request by jhabdas**
Companion article for #34

### CODE REVIEW

**Comment by jhabdas** [comment]
I'll let this one slide due to conflict of interest.

**Comment by jhabdas** [comment]
Okay I changed my mind after seeing all the Contentful articles.

**Comment by jhabdas** [comment]
Article lands in Web Operations weekly http://webopsweekly.com/issues/109

**Comment by verythorough** [comment]
Congrats on getting your article featured in Web Operations Weekly!

I have two concerns with including this article here, both due to the statement, "... so you can close your code without paying through the nose for hosting." First, it's misleading, since you can in fact deploy private repos to Netlify on the free Netlify Pages plan. Second, because this site is intended to be platform-neutral, I think it's important to avoid content that disparages any JAMstack service or technology. By all means give props to your favorites, but please refrain from bringing any others down.

**Comment by jhabdas** [comment]
@verythorough That's good feedback. What you perceive as "disparaging" is actually hyperbole. However, I'm not here to argue semantics of creative writing, and I would never want to mislead my users. I've updated my intro to remove Netlify and, instead, call attention to the free year of hosting on AWS and prevention of plan lock thereafter. I hope that suits your ideal of inclusiveness. If not, please let me know.

**Comment by jhabdas** [comment]
depends on #45

**Comment by jhabdas** [comment]
Added page description meta, enriching the articles section in anticipation of #45

**Comment by verythorough** [comment]
LGTM, too. Sorry, my notifications were getting lost in my personal email, so I've been behind on these.

**Pull request merged**
