### PR TITLE
Add cState to examples

### PR DESCRIPTION
**Pull request by mistermantas**
Hi there!

I liked Netlify’s Statuskit so I decided to take that further with cState. Working on the second dev preview right now, slated for a stable release soon. I think it’d be a good example of the JAMstack!

[cstate/cstate](https://github.com/cstate/cstate)

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *jamstack-site* ready!

Built with commit 8b63615fa50aaf824117b01c09c9abd3482ee0db

https://deploy-preview-124--jamstack-site.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *jamstack-site* ready!

Built with commit 8b63615fa50aaf824117b01c09c9abd3482ee0db

https://deploy-preview-124--jamstack-site.netlify.com

**Comment by mistermantas** [comment]
looks good to me

**Comment by mistermantas** [comment]
@verythorough Any updates on this?

**Comment by verythorough** [comment]
Sorry, that deploy preview notification comment was made by a bot with my user token.

I think @philhawksworth @shortdiv @sw-yx or @DavidWells can help you, though.

**Comment by sw-yx** [comment]
Hi @mistermantas! thank you for your patience as this repo hasn't had a primary maintainer for a few months. you linked to the github whereas we kinda need the main site to remain in line with the other examples in the list. i've gone ahead and corrected for you. thanks for the submission and keep us posted on the netlify twitter on your awesome cstate work!

**Comment by mistermantas** [comment]
I'm in no rush! Thanks for fixing it up.

And, heh, I wrote about cState on [Netlify's blog](https://www.netlify.com/blog/2018/08/17/creating-a-status-page-for-your-company-using-cstate/), not much else to share as of now. :)

**Comment by sw-yx** [comment]
i can merge now :)

**Pull request merged**
