### PR TITLE
Add LDF, JFKT4, TS

### PR DESCRIPTION
**Pull request by mcat**
- add Leonardo Dicaprio Foundation (https://www.leonardodicaprio.org/)
- add JFK Terminal 4 (https://www.jfkt4.nyc/)
- add TakeShape.io (http://www.takeshape.io/)

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *jamstack-site* ready!

Built with commit 9465389606c1dd844d3ac116631382e6ed073675

https://deploy-preview-121--jamstack-site.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *jamstack-site* ready!

Built with commit 9465389606c1dd844d3ac116631382e6ed073675

https://deploy-preview-121--jamstack-site.netlify.com

**Comment by mcat** [comment]
Preview looks good to me!

**Comment by philhawksworth** [comment]
Resolved, added and deployed.

Thanks for these examples, @mcat!
Apologies for the silence. Getting this site and contributions rolling more formally now.

**Pull request closed without merging**
