### PR TITLE
Update ZEIT Now -> Vercel.

### PR DESCRIPTION
**Pull request by leerob**

### CODE REVIEW

**Comment by leerob** [comment]
@zachleat Why was this closed? 🙏

**Comment by zachleat** [comment]
I’m really sorry, it was accidental—we changed our default branch for a new site launch today.

**Comment by zachleat** [comment]
The target branch needs to be `main` now—doesn’t look like I can update it for you (nor reopen this until it’s changed)

**Comment by leerob** [comment]
No worries - opened a new PR 😄

**Pull request closed without merging**
