### PR TITLE
Adding hanhanxue.com site. Updating cita.hr image.

### PR DESCRIPTION
**Pull request by maliMirkec**
Please update the examples.
I have added new website hanhanxue.com.
I have updated the image for cita.hr example.

### CODE REVIEW

**Comment by maliMirkec** [comment]
@verythorough Could I expect this to go live any time soon?

**Comment by verythorough** [comment]
Deploy preview for *jamstack-site* ready!

Built with commit 73a9adf3b93dcdd1b1094377d1d6f36c121287d2

https://deploy-preview-104--jamstack-site.netlify.com

**Comment by maliMirkec** [comment]
@verythorough Can I expect the merge soon?

**Comment by verythorough** [comment]
Sorry for the delay. Though my user makes the deploy preview comments, it's a bot doing the work there. I'm afraid I don't keep up on this repo very closely, though it will be getting more attention (from others) very soon!

**Pull request merged**
