### PR TITLE
added fabuwood.com to examples page

### PR DESCRIPTION
**Pull request by david-genger**
Please see and merge

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *jamstack-site* ready!

Built with commit 2b69c79fb884082c9c8e7913187f54ec45574d60

https://deploy-preview-98--jamstack-site.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *jamstack-site* ready!

Built with commit 2b69c79fb884082c9c8e7913187f54ec45574d60

https://deploy-preview-98--jamstack-site.netlify.com

**Comment by david-genger** [comment]
Looks perfect!

**Comment by david-genger** [comment]
@verythorough What tool do you use to have the same URL for preview deployments even after the branch was updated?

**Comment by verythorough** [comment]
Thanks for the additions, @david-genger! Could you resize your images to the [requested dimensions](https://github.com/jamstack/jamstack.org#contribute-examples) of 596 x 396px?

As for the updating links: Netlify's Deploy Preview links automatically update to show the most recent deploy from the last commit. There are also commit-specific permalinks (like https://5a67624ea114772caeed6c79--jamstack-site.netlify.com/) which always show the same deploy, for the same, specific commit.

**Comment by david-genger** [comment]
Done

**Comment by verythorough** [comment]
Thanks!

**Pull request merged**
