### PR TITLE
Adding personal website.

### PR DESCRIPTION
**Pull request by maliMirkec**

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview ready!

Built with commit 9c8d718721e245fee759dca7f81c450db01657bc

https://deploy-preview-83--jamstack-site.netlify.com

**Comment by verythorough** [comment]
Deploy preview ready!

Built with commit 9c8d718721e245fee759dca7f81c450db01657bc

https://deploy-preview-83--jamstack-site.netlify.com

**Comment by verythorough** [comment]
Nice site! Merging.

**Comment by maliMirkec** [comment]
Thank you! I see that the code is merged, do you know when it will be live at the website?

**Comment by verythorough** [comment]
Oops! Sorry about that. Should be good now! https://jamstack.org/examples/

**Comment by maliMirkec** [comment]
Thanks!

**Pull request merged**
