### PR TITLE
Updates the docs link for ApostropheCMS

### PR DESCRIPTION
**Pull request by abea**
The existing link goes to the previous major version docs.

### CODE REVIEW

**Comment by abea** [comment]
I don't see why this failed the tests.

**Comment by abea** [comment]
@domitriusclark Would someone be able to take a look at this?

**Comment by domitriusclark** [comment]
Hey @abea so sorry for the major delay. 

I'm actively working on the site this week. Currently bringing this repo back into the loop from other owners previously (just hitting my 3rd month!) 

I'll have this in this week with a bunch of others! Seriously appreciate your patience.

**Comment by abea** [comment]
Thanks!

**Pull request merged**
