### PR TITLE
Add Psykose | bipolar to Jamstack

### PR DESCRIPTION
**Pull request by Andersos**

### CODE REVIEW

**Comment by verythorough** [comment]
Thanks for the contribution @Andersos. Sorry for the delay. Could you resize your image to the requested dimensions of 598 x 398? Thank you!

**Comment by verythorough** [comment]
Deploy preview for *jamstack-site* ready!

Built with commit 76de3764551838b8580bcf1a4caf9392c6d90df7

https://deploy-preview-91--jamstack-site.netlify.com

**Comment by Andersos** [comment]
I have updated the resolution for the image and also resolved the conflict.

**Comment by verythorough** [comment]
Deploy preview for *jamstack-site* ready!

Built with commit 3700ab77072f90e24a81ac19283179db1ef03f36

https://deploy-preview-91--jamstack-site.netlify.com

**Comment by verythorough** [comment]
Thanks! LGTM

**Pull request merged**
