### PR TITLE
Add Atomic-Server

### PR DESCRIPTION
**Pull request by joepio**
Hi there! I'd like to add Atomic-Server to this wonderful list :)

### CODE REVIEW

**Comment by georgedoescode** [comment]
Hey! Is this PR ready for review? It's set to `draft` at the moment, but we would be happy to merge it if it's ready 🚀

**Comment by joepio** [comment]
Thanks @georgedoescode! I think so, but I can't see Atomic in [the preview](https://deploy-preview-854--jamstack-site.netlify.app/headless-cms/). Kind of makes me wonder if I missed a step

**Comment by akardet** [comment]
Hey @joepio - It looks like you just forgot to append a file type, `.md`, to your uploaded file! Once you've added that we can go ahead and merge this PR. Thank!

**Comment by joepio** [comment]
> Hey @joepio - It looks like you just forgot to append a file type, `.md`, to your uploaded file! Once you've added that we can go ahead and merge this PR. Thanks!

Whoops - my bad. Fixed!

**Pull request merged**
