### PR TITLE
[WIP] "Add New Community" page

### PR DESCRIPTION
**Pull request by rafaelconde**
Google Chrome 2019-06-06 at 15 48 03@2x

**It has not been tested yet**, but I'm working on a new page with a form for folks to type in information about their new meetups, so the Netlify team can more effectively support them and feature it on the JAMstack site.

### CODE REVIEW

**Comment by PerrySetGo** [comment]
blocked until we get Copy Club magic on this kitten

**Comment by PerrySetGo** [comment]
ok changes have been made - only question i have before merging @rafaelconde  is where do the responses end up - are they handled and emailed to community@ or?

**Comment by klavavej** [comment]
@perrysetgo - 
- responses are available in the UI here https://app.netlify.com/sites/jamstack-site/forms/5cf919675145cb0008023145
- you can set up email (or slack) notifications here https://app.netlify.com/sites/jamstack-site/settings/forms#form-notifications
- details on setting up notifications for forms are in the docs here - https://www.netlify.com/docs/form-handling/#notifications

**Comment by zachleat** [comment]
Really sorry about this, GitHub autoclosed a bunch of PRs when we released a new site design this morning and switched the default branch to `main`.

Do we want to revisit this with the new site design?

**Pull request closed without merging**
