### PR TITLE
Add Hack Cabin

### PR DESCRIPTION
**Pull request by jhabdas**
Companion article on how to build it: https://habd.as/zero-to-http-2-aws-hugo/

### CODE REVIEW

**Comment by verythorough** [comment]
Very cool (though Hack Cabin sounds like kind of a scary place!)

Could you remove the deletion of npm-debug.log? We can fix that in a separate PR.

**Comment by jhabdas** [comment]
> Very cool (though Hack Cabin sounds like kind of a scary place!)

It's not scary at all. It's what most websites used to look like back in the AngelFire and Geocities. It's build using the throwback theme called [After Dark](https://comfusion.github.io/after-dark/), which is build to support terminal-based browsing in in addition to supporting responsive design.

As for the `npm-debug.log`, it was removed automatically by Atom editor and is typically one of the first things added to a `.gitignore` file. Is there a particular reason you'd want to keep it?

**Comment by verythorough** [comment]
Oh, I like the design--I thought the name sounds like the title of a horror movie. 😛 

`npm-debug.log` is actually in the `.gitignore`, but apparently got in there before that. I plan to remove it, but in a separate commit.

**Comment by jhabdas** [comment]
The term "Hack Cabin" was coined by [@eanplatter](https://github.com/eanplatter), curator of the React Newsletter. It means a place of solitude for which one can hack.

I submitted #35, which is necessary so I can rebase for this pull.

@verythorough

**Comment by jhabdas** [comment]
@verythorough all set

**Comment by verythorough** [comment]
Perfect! Thanks so much.

(Your hack cabin description makes me want to be in one right now. Of course, I knew that was the "hack" meaning you intended, but I can't help imagining slasher movies.)

**Comment by verythorough** [comment]
Oops, silly me, this is what I get for not checking the deploy preview. The last two sites have irregularly sized screenshots. I'll file an issue to add dimensions to the contributor instructions, and fix the existing images.

**Comment by jhabdas** [comment]
@verythorough for an example on how hugo themes handles this please see https://github.com/spf13/hugoThemes#adding-a-theme-to-the-list

**Pull request merged**
