### PR TITLE
Adds sorting and filters to Headless CMS and Site Generator pages

### LINKED ISSUE #401: Re-add filters and sorting by programming lanuage on Site Generators and Headless CMS pages
Hi, it will be useful to sort [generator cards](https://jamstack.org/generators/) by programming language.
Example attached below, text names can be replaced with logos
generators-sorting-update

### PR DESCRIPTION
**Pull request by zachleat**
~~#470 must be merged first.~~

Fixes #401 (filtering and sorting)

https://zl-filters--jamstack-site.netlify.app/generators/
https://zl-filters--jamstack-site.netlify.app/headless-cms/

### CODE REVIEW

**Comment by zachleat** [comment]
Fixes part of #401

**Comment by noraj** [comment]
This is a bit unrelated to those filters but you could want to keep this in mind.

On staticgen.org there were a bunch of linters, for example to check license names.

After https://github.com/netlify/staticgen/pull/603 and https://github.com/netlify/staticgen/pull/643, they implemented a CI task to check the license name of new committed tools are respecting the SPDX format.

You should maybe also create a whitelist of backend langue & template language so teh CI emit a warning when a new one is used this will avoid name drifting and having a list with python, Python, Python 3, python3, etc.

**Comment by zachleat** [comment]
@noraj Excellent feedback! I wasn’t aware of that—I just added a console warning if there are invalid license names using `spdx-checker`. It doesn’t fail the build but it should help with drift.

Right now there are two invalid ones:

image

**Comment by zachleat** [comment]
Alright this one is officially ready for a look 👍🏻

**Review by philhawksworth — APPROVED** [review]
This looks great!

**Pull request merged**
