### PR TITLE
Add creative designs guru

### PR DESCRIPTION
**Pull request by ixartz**

### CODE REVIEW

**Comment by ixartz** [comment]
It seems PR are failing without any reasons. It also fails when I make an empty pull request, a pull request without any change from master and it also fails.

**Comment by zachleat** [comment]
Really sorry about this, GitHub autoclosed a bunch of PRs when we released a new site design this morning and switched the default branch to `main`. Can you change the target to `main` and then I can reopen?

**Comment by ixartz** [comment]
@zachleat Thank you for letting me know. I have just created a new pull request https://github.com/jamstack/jamstack.org/pull/382.

This is one was pretty old and follow the old structure and the git history was a little hard to merge.
So, I have created a new pull request and I have also taken the chance to make a new screenshot.

Thank you in advance.

**Comment by zachleat** [comment]
Perfect, thank you!

**Pull request closed without merging**
