### PR TITLE
Pushing update to jamstack.org examples

### PR DESCRIPTION
**Pull request by ntharani**

### CODE REVIEW

**Comment by verythorough** [comment]
Looks great! Thanks for adding!

**Comment by jhabdas** [comment]
Way to add no information. Great job!

**Comment by verythorough** [comment]
@jhabdas Sarcasm isn't welcome here. If you have constructive feedback on how to properly describe a PR, feel free. We can also improve our contributor docs and add PR templates to provide more proactive guidance.

**Comment by ntharani** [comment]
I'm still new to contributing to merge commits - have done a lot of stuff locally. So very open to advice. I added the description to the yaml file as they asked and copied the template.

**Comment by verythorough** [comment]
No problem, @ntharani. Your contribution to the yaml file was fine. It would have been easier to see what you PR was about (for example, in the subject line of my email alert), if your commit message described what you were updating, for example, "Add Hyper Static to examples page." We can add this advice to the contributing guidelines.

**Comment by jhabdas** [comment]
@ntharani I didn't realize the contribution guidelines in the README didn't provide much guidance for you. That's my bad. Some projects tend to overdo it with templates and guidance but there are just a few basic protocols which will take you fare.

> So very open to advice.

Thanks for being open. I've found the must efficient workflow to be this, which requires a little bit of a learning curve but will make you look like a tenured pro in no time:

- https://hub.github.com/ - enables you fork repos and open pulls from command line
- https://conventionalcommits.org/ - helps structure parsable commits which can be used to autogenerate change logs and close issues automatically

If you have any questions on using them, please feel free to reach out. I give my time for free to anyone interested in learning, as I've found the beginners are actually the teachers.

**Pull request merged**
