### PR TITLE
docs(examples): add alt text and title for thumbs

### PR DESCRIPTION
**Pull request by jhabdas**
adds alt text to example thumbs for improved aural experience, uses example description to provide
thumbnail mouseover text and removes self-closing tag on void element

### CODE REVIEW

**Comment by erquhart** [comment]
Thanks @jhabdas! Thumbs up on the alt text, but not certain about the description popping up on hover. It may be beneficial to simply show descriptions under the example title, though. Thoughts @verythorough?

**Comment by jhabdas** [comment]
@erquhart could do a [popper](https://popper.js.org/) to improve UX a little more. I added this because nothing is currently being done with descriptions AFIACT /cc @verythorough

**Comment by verythorough** [comment]
Thanks, @jhabdas, for catching this accessibility issue! I have some suggestions for the implementation. In this particular case, the images are decorative, and repeating the website title along with the words "thumbnail image" doesn't enhance the screenreader experience, aside from giving some text to go with the link surrounding the image. (And that part *is* important!)

I suggest instead making the site titles below the thumbnails into links, and hiding the thumbnails from screenreaders with empty `alt` attributes and `aria-hidden="true"` on the links surrounding the images.

(See [this article on WebAIM](http://webaim.org/blog/alt-text-and-linked-images/) for a lengthier explanation, and consider inspecting YouTube thumbnails for an implementation example.)

I also recommend removing the descriptions altogether. Their inclusion in the data file is a holdover from a previous design, before we started including the "stack" for each example. We wanted to put more emphasis on *how* the sites were made, rather than what they were about.

**Comment by jhabdas** [comment]
@verythorough thanks for the feedback. would you mind reopening this so I can address your feedback please?

**Comment by verythorough** [comment]
lol, there I go again, closing and commenting! Sorry!

**Comment by verythorough** [comment]
Incidentally, @jhabdas, another option would be to wrap the entire block in a link, as is done for the videos on the Resources page. You can even piggyback on the existing `.resources .video` styles to avoid turning everything aqua.

(In both cases, though, I would add empty `alt` attributes to the images. Feel free to add that fix to the video thumbnails in this PR if you're so inclined.)

**Comment by jhabdas** [comment]
Now we're talkin'

**Comment by jhabdas** [comment]
> In this particular case, the images are decorative

Disagree. Because example images are not _trim_ they are not decorative and should not be hidden from aural user agents. Content images help enrich the semantic value of the page and improve screen reader experience, WIA-ARIA notwithstanding.

> I suggest instead making the site titles below the thumbnails into links

No need. The page is already optimized for mobile as the entire grouping of related content (image, article title and keywords are wrapped in an anchor tag.

> I also recommend removing the descriptions altogether.

Out of scope.

---

I've pushed up a new commit to remove the `title` attribute, so now we're only improving the semantic value of the page for aural UAs.

**Comment by jhabdas** [comment]
Bump on a one-line code change. I hope your conference was a success.

**Comment by verythorough** [comment]
Sorry, as you might imagine, it's been a busy couple of weeks!

I really have to stand firm in saying that repeating adjacent content is not an appropriate use of alt text. The link I included in a previous comment, as well as any guide you will find on writing alt text, will confirm this assertion. If I navigate your deploy preview with a screen reader, I'm presented with, "...Dusk screenshot Dusk... Sequoia Capital screenshot Sequoia Capital...." I don't believe this is an improvement in user experience.

There are actually a number of accessibility improvements that *could* be made to this page, including: marking up the "stacks" as `<ul>`s, changing the site titles to `<h2>`s, and pulling the decorative dots at the top of each screenshot out of the html markup. If you'd like to take a stab at these, it would be a fantastic contribution.

As for the alt attributes, however, they absolutely should be included, but should be blank.

**Comment by jhabdas** [comment]
Closing pull as conversation is devolving into pedantics.

**Pull request closed without merging**
