### PR TITLE
perf($examples): compress hackcabin thumbnail

### PR DESCRIPTION
**Pull request by jhabdas**
reduces file size of existing thumb ~276% on top of the ImageOptim compressed version with no perceptible loss in quality. final size ~98K.

method: `brew install pngquant && pngquant --quality=0-10 hackcabin.png`

related #71

### CODE REVIEW

**Comment by jhabdas** [comment]
Rebased and force pushed.

**Comment by jhabdas** [comment]
@DirtyF would you do the honors of updating my site image for me?

**Comment by jhabdas** [comment]
Sigh.

**Comment by verythorough** [comment]
Sorry the response didn't come quick enough for you. Merging this to merge #75 without dealing with the merge conflict.

**Comment by jhabdas** [comment]
It's not that it didn't come quick enough. It's that my changes were steamrolled. That's why I left.

**Pull request merged**
