### PR TITLE
Add legal links to footer

### PR DESCRIPTION
**Pull request by akardet**
Adding legal links to footer

### CODE REVIEW

**Comment by stephan1echung** [comment]
screenshot

@akardet Let's remove the Trust Center link so there's not a lone link at the bottom
<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Chrome 111.0.0.0 on Mac OS 10.15.7
Viewport:  1920 x 824 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-879--jamstack-site.netlify.app%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=111.0&resolution=1920x824&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-879--jamstack-site.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=642f006f820ff8000873fbc4&commentID=642f07dfaf0ad805d0b9df8d&resolution=resolved)

**Comment by akardet** [comment]
> @akardet Let's remove the Trust Center link so there's not a lone link at the bottom

@stephan1echung - I changed it to 3 columns so it lays out better

**Comment by stephan1echung** [comment]
screenshot

@akardet ooh good idea! Are the columns centered though? The embedded video makes it not seem so 🧐
<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Chrome 111.0.0.0 on Mac OS 10.15.7
Viewport:  1920 x 824 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-879--jamstack-site.netlify.app%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=111.0&resolution=1920x824&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-879--jamstack-site.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=642f0a897b32390008b5be7a&commentID=642f1ca1fca06a0492d0cb6c&resolution=resolved)

**Comment by akardet** [comment]
@stephan1echung - I'd say it's fine to leave as is, as the words break better for all viewports so it behaves more responsively.

**Review by stephan1echung — APPROVED** [review]
Got it, sounds good then let's merge! :shipit:

**Pull request merged**
