### PR TITLE
Add NSHipster.com to List of Examples

### PR DESCRIPTION
**Pull request by mattt**
nshipster-jamstack-screenshot

### CODE REVIEW

**Comment by mattt** [comment]
Checks are failing, but it doesn't look like it was caused by this commit in particular.

Here's what I got when running a fresh clone of the repository (node v8.10.0, npm 6.4.1):

```terminal
$ npm run start
fnm: It seems 'node' is not a valid version number.
Hint: Examples of valid node versions:
       v5.10.1
        latest
          0.12
           lts

> victor-hugo@1.0.0 start /Users/mattt/Sites/jamstack.org
> gulp server

[11:12:51] Failed to load external module @babel/register
[11:12:51] Requiring external module babel-register
...
```

**Comment by mattt** [comment]
9990fad fixed the "It seems 'node' is not a valid version number." error, but checks are still failing on `11:26:47 AM: > gulp build-preview`.

Taking another look at the logs, I noticed that there's a conflict in the build command specified in `netlify.toml` vs. the Netlify dashboard. Right now, the TOML file uses `build-preview`, which doesn't seem right at first glance...

**Comment by mattt** [comment]
I just realized that I was previewing locally with `gulp server` instead of `gulp build`, so I was confused why it was succeeding locally but failing on deploy. I can now replicate the issue locally. 

By all accounts, this appears to be related to https://github.com/gulpjs/gulp/issues/2246. It looks like our options are to either upgrade to `gulp@next` to support new Node versions or specify an older version of node to a version compatible with 3.9.1.

**Comment by mattt** [comment]
Alright, I updated to Gulp 4 with c6043f8. This required some slight modifications to `gulpfile.babel.js` to migrate to the new task API (instead of an array of dependencies, you specify `gulp.series(...)` or `gulp.parallel(...)`).

**Comment by philhawksworth** [comment]
Closed by #285

**Comment by mattt** [comment]
Awesome. Thanks so much, @philhawksworth!

**Pull request closed without merging**
