### PR TITLE
Added Story Breeding to JAMStack examples

### PR DESCRIPTION
**Pull request by johnpaulada**
I added my site, https://storybreeding.surge.sh, to the JAMStack examples. 😄

### CODE REVIEW

**Comment by verythorough** [comment]
Thanks for the contribution @johnpaulada. Sorry for the delay. Could you resize your image to the [requested dimensions](https://github.com/jamstack/jamstack.org#contribute-examples) of 598 x 398? Thank you!

**Comment by verythorough** [comment]
Deploy preview for *jamstack-site* ready!

Built with commit b2cc535efb39b98eee50a14b32644c7a29f9c6f4

https://deploy-preview-90--jamstack-site.netlify.com

**Comment by johnpaulada** [comment]
Hi @verythorough ! I've made the necessary changes.

**Comment by verythorough** [comment]
Thanks!

**Pull request merged**
