### PR TITLE
Add adaptiveprogrammer.com to JAMstack examples

### PR DESCRIPTION
**Pull request by peterpuglisi**
Request to contribute example site to the JAMstack community.

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview ready!

Built with commit d2320637bda19ae89ac3dee4f68dc0619d5b05af

https://deploy-preview-95--jamstack-site.netlify.com

**Comment by verythorough** [comment]
Deploy preview ready!

Built with commit d2320637bda19ae89ac3dee4f68dc0619d5b05af

https://deploy-preview-95--jamstack-site.netlify.com

**Comment by DirtyF** [comment]
I'm not sure if a basic Hugo blog without JavaScript and APis use qualifies for the JAMstack website 🤔

**Comment by verythorough** [comment]
Technically, Disqus is an API, and you have to use JavaScript to include it in your site, so...
Besides, I think one of the nice things about the examples page is that it can show a wide range of projects that can be made on the JAMstack. Maybe at some point, we might want to put a featured section at the top for sites that are doing particularly interesting or unexpected things.

Thanks for the contribution, @peterpuglisi!

**Pull request merged**
